# Generated by Django 3.0.7 on 2020-06-20 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0002_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exter',
        ),
    ]
