# Generated by Django 3.0.6 on 2020-06-13 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0006_ostad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ostad',
            name='uni',
        ),
    ]
