# Generated by Django 3.0.7 on 2020-06-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0008_ostad_uni'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='activate',
            field=models.BooleanField(default=True),
        ),
    ]
