# Generated by Django 3.0.7 on 2020-06-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0010_auto_20200613_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
            ],
        ),
    ]
