# Generated by Django 3.0.7 on 2020-06-13 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0011_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
