# Generated by Django 3.0.7 on 2020-06-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0011_vahed_elam_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vahed',
            name='klas_id',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
