# Generated by Django 3.0.7 on 2020-06-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0012_vahed_klas_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ostad',
            name='time',
            field=models.CharField(default=' ', max_length=500),
            preserve_default=False,
        ),
    ]
