# Generated by Django 3.0.7 on 2020-06-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0012_delete_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='College',
            field=models.CharField(choices=[('------------------------------------------------------------------------------', '------------------------------------------------------------------------------'), ('فنی مهندسی', 'فنی مهندسی'), ('علوم پایه', 'علوم پایه'), ('علوم اقتصادی و اداری', 'علوم اقتصادی و اداری'), ('علوم سیاسی', 'علوم سیاسی'), ('علوم دریایی', 'علوم دریایی')], default=' ', max_length=2000),
            preserve_default=False,
        ),
    ]
