# Generated by Django 3.0.7 on 2020-06-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0014_auto_20200623_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='elam',
            name='reject',
            field=models.BooleanField(default=False),
        ),
    ]
