# Generated by Django 3.0.7 on 2020-06-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0017_auto_20200614_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='ostad',
            name='dars1',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ostad',
            name='dars2',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ostad',
            name='dars3',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ostad',
            name='dars4',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
