# Generated by Django 3.0.7 on 2020-06-14 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0018_auto_20200614_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elam',
            name='fields',
        ),
        migrations.RemoveField(
            model_name='elam',
            name='term',
        ),
    ]
