# Generated by Django 3.0.7 on 2020-06-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0019_auto_20200614_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='elam',
            name='username',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
