# Generated by Django 3.0.7 on 2020-06-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0019_elam_accept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elam',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
