# Generated by Django 3.0.7 on 2020-06-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0020_elam_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exter2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('ostad', models.CharField(max_length=200)),
                ('dars', models.CharField(max_length=200)),
                ('college', models.CharField(max_length=200)),
            ],
        ),
    ]
