# Generated by Django 3.0.7 on 2020-07-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0020_auto_20200625_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='vahed',
            name='ostad_id',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
