# Generated by Django 3.0.7 on 2020-07-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0022_elam_ostad_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vahed',
            name='laghv',
            field=models.BooleanField(default=False),
        ),
    ]
