# Generated by Django 3.0.7 on 2020-07-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0023_vahed_laghv'),
    ]

    operations = [
        migrations.AddField(
            model_name='vahed',
            name='uni',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
