# Generated by Django 3.0.7 on 2020-06-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0015_auto_20200614_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='elam',
            name='term',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
