# Generated by Django 3.0.7 on 2020-06-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0021_exter2'),
    ]

    operations = [
        migrations.AddField(
            model_name='elam',
            name='phone',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
