# Generated by Django 3.0.6 on 2020-05-29 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='live',
            new_name='student_live',
        ),
    ]
