# Generated by Django 3.0.6 on 2020-05-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='question_text',
        ),
        migrations.AddField(
            model_name='student',
            name='student_last_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_name',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
