# Generated by Django 3.0.6 on 2020-06-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='pub_date',
            new_name='birthday',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='admin_last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='admin_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='admin_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='Admin_username',
            new_name='username',
        ),
        migrations.AddField(
            model_name='admin',
            name='public_date',
            field=models.DateTimeField(null=True),
        ),
    ]
