# Generated by Django 3.0.7 on 2020-06-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='uni',
            field=models.CharField(choices=[('------------------------------------------------------------------------------', '------------------------------------------------------------------------------'), ('تهران', 'تهران'), ('مازندران', 'مازندران'), ('اصفهان', 'اصفهان'), ('امیرکبیر', 'امیر کبیر'), ('صنعتی شریف', 'صنعتی شریف'), ('شهید بهشتی', 'شهید بهشتی'), ('صنعتی اصفهان', 'صنعتی اصفهان'), ('علم و صنعت', 'علم و صنعت'), ('خواجه نصیر', 'خواجه نصیر'), ('شیراز', 'شیراز'), ('نوشیروانی', 'نوشیروانی'), ('تبریز', 'تبریز')], default=' ', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elam',
            name='uni',
            field=models.CharField(default=' ', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='klass',
            name='uni',
            field=models.CharField(default=' ', max_length=2000),
            preserve_default=False,
        ),
    ]
