# Generated by Django 3.0.7 on 2020-07-13 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vahed',
            name='birthday',
        ),
    ]
