# Generated by Django 3.0.6 on 2020-05-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0002_auto_20200529_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birthdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
