# Generated by Django 3.0.6 on 2020-06-05 06:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0002_auto_20200605_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='public_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 5, 6, 19, 8, 92114, tzinfo=utc)),
        ),
    ]
