# Generated by Django 3.0.7 on 2020-06-15 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0002_auto_20200615_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ostad',
            name='College',
        ),
    ]
