# Generated by Django 3.0.6 on 2020-05-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0002_auto_20200525_0232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=200)),
                ('admin_last_name', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
