# Generated by Django 3.0.6 on 2020-06-06 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0002_auto_20200605_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='login_times',
            field=models.CharField(default=' ', max_length=10000),
            preserve_default=False,
        ),
    ]
