# Generated by Django 3.0.7 on 2020-07-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0002_remove_vahed_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='vahed',
            name='emtehan_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
