# Generated by Django 3.0.7 on 2020-07-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0003_remove_admin2_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('public_date', models.DateTimeField(null=True)),
                ('login_date', models.DateTimeField(null=True)),
                ('login_date2', models.DateTimeField(null=True)),
                ('login_times', models.CharField(max_length=10000)),
                ('online', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='admin2',
            name='birthday',
        ),
    ]
