# Generated by Django 3.0.7 on 2020-07-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0003_student_darses'),
    ]

    operations = [
        migrations.AddField(
            model_name='elam',
            name='vahed',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vahed',
            name='vahed2',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
