# Generated by Django 3.0.7 on 2020-06-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0003_remove_ostad_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='klass',
            name='por',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
