# Generated by Django 3.0.6 on 2020-05-29 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0003_student_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='student',
            name='field',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parents_phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_live',
        ),
    ]
