# Generated by Django 3.0.7 on 2020-06-15 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0003_auto_20200615_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elam',
            old_name='groh',
            new_name='goruh',
        ),
    ]
