# Generated by Django 3.0.6 on 2020-05-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0003_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='admin_password',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_password',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
