# Generated by Django 3.0.6 on 2020-06-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0003_student_login_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='login_times',
            field=models.CharField(default=' ', max_length=10000),
            preserve_default=False,
        ),
    ]
