# Generated by Django 3.0.7 on 2020-07-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0004_auto_20200719_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_leader',
            field=models.BooleanField(default=False),
        ),
    ]
