# Generated by Django 3.0.7 on 2020-07-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0004_auto_20200715_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='darses',
            field=models.CharField(blank=True, max_length=1000000),
        ),
        migrations.AlterField(
            model_name='vahed',
            name='students',
            field=models.CharField(blank=True, max_length=1000000),
        ),
    ]
