# Generated by Django 3.0.6 on 2020-06-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0004_admin_login_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
