# Generated by Django 3.0.7 on 2020-06-20 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0004_delete_exter2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='Admin2',
        ),
    ]
