# Generated by Django 3.0.7 on 2020-06-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0004_auto_20200615_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='exter2',
            name='goruh',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
