# Generated by Django 3.0.7 on 2020-07-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0005_auto_20200715_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='time',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
