# Generated by Django 3.0.7 on 2020-06-20 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0005_auto_20200620_2236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='klass',
            old_name='por',
            new_name='khali',
        ),
    ]
