# Generated by Django 3.0.7 on 2020-07-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0006_student_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='nomre',
            field=models.CharField(blank=True, max_length=1000000),
        ),
        migrations.AddField(
            model_name='vahed',
            name='nomre',
            field=models.CharField(blank=True, max_length=1000000),
        ),
    ]
