# Generated by Django 3.0.7 on 2020-07-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0006_auto_20200719_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='boss',
            name='phone',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
