# Generated by Django 3.0.7 on 2020-06-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0006_auto_20200621_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='klass',
            name='time',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
