# Generated by Django 3.0.6 on 2020-05-27 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0006_auto_20200526_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exter_username', models.CharField(max_length=200)),
            ],
        ),
    ]
