# Generated by Django 3.0.6 on 2020-05-27 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0007_exter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exter',
            old_name='exter_username',
            new_name='exter_name',
        ),
    ]
