# Generated by Django 3.0.7 on 2020-06-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0007_klass_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vahed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dars', models.CharField(max_length=200)),
                ('goruh', models.CharField(max_length=200)),
                ('ostad', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('college', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
