# Generated by Django 3.0.6 on 2020-05-30 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0007_auto_20200530_0745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='pub_date',
            new_name='birthday',
        ),
    ]
