# Generated by Django 3.0.7 on 2020-07-18 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0007_boss_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='boss',
            name='uni',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
