# Generated by Django 3.0.7 on 2020-07-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0007_auto_20200715_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='vahed',
            name='final',
            field=models.BooleanField(default=False),
        ),
    ]
