# Generated by Django 3.0.7 on 2020-06-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0008_vahed'),
    ]

    operations = [
        migrations.AddField(
            model_name='vahed',
            name='dars_code',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
