# Generated by Django 3.0.7 on 2020-07-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0008_vahed_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klass',
            name='t01',
        ),
        migrations.RemoveField(
            model_name='klass',
            name='t02',
        ),
        migrations.RemoveField(
            model_name='klass',
            name='t03',
        ),
        migrations.RemoveField(
            model_name='klass',
            name='t04',
        ),
        migrations.RemoveField(
            model_name='klass',
            name='t05',
        ),
        migrations.RemoveField(
            model_name='klass',
            name='t11',
        ),
        migrations.RemoveField(
            model_name='klass',
            name='t12',
        ),
        migrations.RemoveField(
            model_name='klass',
            name='t13',
        ),
        migrations.RemoveField(
            model_name='klass',
            name='t14',
        ),
        migrations.RemoveField(
            model_name='klass',
            name='t15',
        ),
        migrations.RemoveField(
            model_name='klass',
            name='t21',
        ),
        migrations.RemoveField(
            model_name='klass',
            name='t22',
        ),
        migrations.RemoveField(
            model_name='klass',
            name='t23',
        ),
        migrations.RemoveField(
            model_name='klass',
            name='t24',
        ),
        migrations.RemoveField(
            model_name='klass',
            name='t25',
        ),
        migrations.RemoveField(
            model_name='klass',
            name='t31',
        ),
        migrations.RemoveField(
            model_name='klass',
            name='t32',
        ),
        migrations.RemoveField(
            model_name='klass',
            name='t33',
        ),
        migrations.RemoveField(
            model_name='klass',
            name='t34',
        ),
        migrations.RemoveField(
            model_name='klass',
            name='t35',
        ),
        migrations.RemoveField(
            model_name='klass',
            name='t41',
        ),
        migrations.RemoveField(
            model_name='klass',
            name='t42',
        ),
        migrations.RemoveField(
            model_name='klass',
            name='t43',
        ),
        migrations.RemoveField(
            model_name='klass',
            name='t44',
        ),
        migrations.RemoveField(
            model_name='klass',
            name='t45',
        ),
        migrations.AddField(
            model_name='klass',
            name='barname',
            field=models.CharField(blank=True, max_length=200000000),
        ),
    ]
