# Generated by Django 3.0.7 on 2020-07-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0008_boss_uni'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin2',
            name='phone',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
