# Generated by Django 3.0.6 on 2020-05-30 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0008_auto_20200530_0746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='birthday',
        ),
    ]
