# Generated by Django 3.0.6 on 2020-05-28 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0008_auto_20200527_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='exter',
            name='number',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
