# Generated by Django 3.0.7 on 2020-07-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0009_auto_20200716_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klass',
            name='barname',
        ),
        migrations.AddField(
            model_name='klass',
            name='vaheds',
            field=models.CharField(blank=True, max_length=200000000),
        ),
    ]
