# Generated by Django 3.0.7 on 2020-07-19 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0009_admin2_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin2',
            name='ejaze',
            field=models.CharField(default=' ', max_length=10000),
            preserve_default=False,
        ),
    ]
