# Generated by Django 3.0.7 on 2020-06-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0009_vahed_dars_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='elam',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
