# Generated by Django 3.0.7 on 2020-07-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0010_auto_20200716_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vahed',
            name='nomre',
            field=models.BooleanField(default=False),
        ),
    ]
