# Generated by Django 3.0.7 on 2020-06-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0010_elam_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='vahed',
            name='elam_id',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
