# Generated by Django 3.0.7 on 2020-07-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0010_admin2_ejaze'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elam_id', models.CharField(max_length=200)),
                ('ostad_id', models.CharField(max_length=200)),
                ('time_klass', models.CharField(max_length=500)),
            ],
        ),
    ]
