# Generated by Django 3.0.7 on 2020-07-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0011_exter'),
    ]

    operations = [
        migrations.AddField(
            model_name='exter',
            name='time',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
