# Generated by Django 3.0.6 on 2020-06-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0011_auto_20200603_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='College',
            field=models.CharField(choices=[('----------------------------------------------------', '----------------------------------------------------'), ('فنی مهندسی', 'فنی مهندسی'), ('علوم پایه', 'علوم پایه'), ('اقتصاد', 'اقتصاد'), ('علوم سیاسی', 'علوم سیاسی'), ('اقیانوس', 'اقیانوس'), ('شیمی', 'شیمی')], max_length=200),
        ),
    ]
