# Generated by Django 3.0.7 on 2020-07-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0011_auto_20200716_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='vahed',
            name='nomre2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vahed',
            name='nomre',
            field=models.CharField(blank=True, max_length=1000000),
        ),
    ]
