# Generated by Django 3.0.7 on 2020-07-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0012_auto_20200716_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='vahed',
            name='capacity2',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
