# Generated by Django 3.0.7 on 2020-07-19 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0012_exter_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vahed',
            name='klas_id',
        ),
    ]
