# Generated by Django 3.0.7 on 2020-06-23 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0013_ostad_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='vahed',
            name='capacity',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ostad',
            name='dars1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ostad',
            name='dars2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ostad',
            name='dars3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ostad',
            name='dars4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ostad',
            name='field',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ostad',
            name='grade',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ostad',
            name='time',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
