# Generated by Django 3.0.7 on 2020-07-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0013_remove_vahed_klas_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ip_address',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
