# Generated by Django 3.0.7 on 2020-07-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0013_vahed_capacity2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vahed',
            name='capacity2',
            field=models.CharField(default=models.CharField(max_length=200), max_length=200),
        ),
    ]
