# Generated by Django 3.0.7 on 2020-06-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0014_elam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elam',
            name='time',
            field=models.CharField(max_length=1000),
        ),
    ]
