# Generated by Django 3.0.7 on 2020-07-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0014_account_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='lang',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
    ]
