# Generated by Django 3.0.7 on 2020-07-19 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0015_account_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin2',
            name='lang',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boss',
            name='lang',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leader',
            name='lang',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ostad',
            name='lang',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='lang',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
    ]
