# Generated by Django 3.0.6 on 2020-06-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0015_auto_20200603_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(choices=[('شیعه 12 امامی', 'شیعه 12 امامی'), ('شیعه 7 امامی', 'شیعه 7 امامی'), ('مسیحی', 'مسیحی'), ('زرتشت', 'زرتشت'), ('بهایی', 'بهایی'), ('یهودی', 'یهودی')], default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
