# Generated by Django 3.0.7 on 2020-07-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0015_auto_20200716_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='vahed',
            name='por',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
