# Generated by Django 3.0.7 on 2020-07-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0016_vahed_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vahed',
            name='por',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
