# Generated by Django 3.0.7 on 2020-07-21 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0016_auto_20200720_0428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forget1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('uni', models.CharField(max_length=200)),
                ('college', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Forget2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('uni', models.CharField(max_length=200)),
            ],
        ),
    ]
