# Generated by Django 3.0.7 on 2020-06-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0016_elam_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='elam',
            name='vaziat',
            field=models.CharField(default=' ', max_length=2000),
            preserve_default=False,
        ),
    ]
