# Generated by Django 3.0.7 on 2020-06-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0016_elam_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='field',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ostad',
            name='field',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ostad',
            name='grade',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
