# Generated by Django 3.0.7 on 2020-07-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0017_auto_20200716_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vahed',
            name='por',
            field=models.CharField(blank=True, default='0', max_length=200),
        ),
    ]
