# Generated by Django 3.0.7 on 2020-06-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0017_elam_vaziat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elam',
            name='vaziat',
            field=models.CharField(default='درحال بررسی', max_length=2000),
        ),
    ]
