# Generated by Django 3.0.7 on 2020-07-21 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0017_forget1_forget2'),
    ]

    operations = [
        migrations.AddField(
            model_name='forget1',
            name='a',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='forget1',
            name='s',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='forget2',
            name='bs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='forget2',
            name='os',
            field=models.BooleanField(default=False),
        ),
    ]
