# Generated by Django 3.0.7 on 2020-07-21 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0018_auto_20200721_0457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('uni', models.CharField(max_length=200)),
                ('college', models.CharField(max_length=200)),
                ('s', models.BooleanField(default=False)),
                ('a', models.BooleanField(default=False)),
                ('os', models.BooleanField(default=False)),
                ('bs', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Forget1',
        ),
        migrations.DeleteModel(
            name='Forget2',
        ),
    ]
