# Generated by Django 3.0.7 on 2020-07-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0019_auto_20200716_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sex',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
