# Generated by Django 3.0.7 on 2020-07-21 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0019_auto_20200721_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='forget',
            name='public_date',
            field=models.DateTimeField(null=True),
        ),
    ]
