# Generated by Django 3.0.7 on 2020-07-21 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0020_forget_public_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='forget',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
