# Generated by Django 3.0.7 on 2020-07-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0021_vahed_ostad_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='elam',
            name='ostad_id',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
