# Generated by Django 3.0.7 on 2020-07-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0021_auto_20200716_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Darkhast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=200)),
                ('text2', models.TextField(max_length=20000)),
                ('uni', models.CharField(max_length=200)),
                ('college', models.CharField(max_length=200)),
            ],
        ),
    ]
