# Generated by Django 3.0.7 on 2020-07-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0022_darkhast'),
    ]

    operations = [
        migrations.AddField(
            model_name='darkhast',
            name='vahed_id',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
