# Generated by Django 3.0.7 on 2020-07-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0023_darkhast_vahed_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='darkhast',
            name='accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='darkhast',
            name='reject',
            field=models.BooleanField(default=False),
        ),
    ]
