# Generated by Django 3.0.7 on 2020-07-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0024_auto_20200717_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='darkhast',
            name='ostad_id',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='darkhast',
            name='text3',
            field=models.TextField(default=' ', max_length=20000),
            preserve_default=False,
        ),
    ]
