# Generated by Django 3.0.7 on 2020-07-22 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0024_auto_20200722_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='exter',
            name='code',
            field=models.CharField(default=' ', max_length=5000),
            preserve_default=False,
        ),
    ]
