# Generated by Django 3.0.7 on 2020-07-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0025_exter_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin2',
            name='College',
            field=models.CharField(max_length=2000),
        ),
    ]
