# Generated by Django 3.0.7 on 2020-07-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0025_auto_20200717_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Darkhast2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=200)),
                ('vahed_id', models.CharField(max_length=200)),
                ('ostad_id', models.CharField(max_length=200)),
                ('text2', models.TextField(max_length=20000)),
                ('text3', models.TextField(max_length=20000)),
                ('uni', models.CharField(max_length=200)),
                ('college', models.CharField(max_length=200)),
                ('reject', models.BooleanField(default=False)),
                ('accept', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='darkhast',
            name='ostad_id',
        ),
        migrations.RemoveField(
            model_name='darkhast',
            name='text3',
        ),
    ]
