# Generated by Django 3.0.7 on 2020-07-17 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0026_auto_20200717_1903'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Darkhast2',
            new_name='Eteraz',
        ),
    ]
