# Generated by Django 3.0.7 on 2020-07-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0027_auto_20200717_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin2',
            name='login_date2',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ostad',
            name='login_date2',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='login_date2',
            field=models.DateTimeField(null=True),
        ),
    ]
